[build]
  publish = "."  
  
[functions]
  directory = "netlify/functions"

  [[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
    Content-Type = "application/javascript"